"""
Maze Runner 2
Move around a maze and try to escape. Maze files are generated by mazemakerrec.py
data/maze11x11s1.txt
data/maze75x11s1.txt

Level: Intermediate
What I learned:
    TODO later
        Good lesson on wall detection
        instead of global keyword in a class use def __init__(self)
        os.getcwd())
        os.listdir():
"""

import sys, os
from maze import Maze, WALL, EMPTY, START, EXIT

def main():
    # Get the maze file's filename from the user
    while True:
        print('Examples: data/maze11x11s1.txt\nExamples: data/maze75x11s1.txt\nEnter the filename of the maze (or LIST or QUIT):')
        filename = input('> ')

        # List all the maze files in the current folder
        if filename.upper() == 'LIST':
            print('Maze files found in', os.getcwd())

            for fileInCurrentFolder in os.listdir():
                if (fileInCurrentFolder.startswith('maze') and fileInCurrentFolder.endswith('.txt')):
                    print('  ', fileInCurrentFolder)
            continue

        if filename.upper() == 'QUIT':
            sys.exit()

        if os.path.exists(filename):
            break
        print('There is no file named', filename)

    # Load the maze from a file
    mazeFile = open("data/" + filename)         # Note: data folder
    maze = {}
    lines = mazeFile.readlines()
    playerx = None
    playery = None
    exitx = None
    exity = None
    y = 0

    for line in lines:
        WIDTH = len(line.rstrip())
        for x, character in enumerate(line.rstrip()):
            assert character in (WALL, EMPTY, START, EXIT), 'Invalid character at column {}, line {}'.format(x + 1, y + 1)
            if character in (WALL, EMPTY):
                maze[(x, y)] = character
            elif character == START:
                playerx, playery = x, y
                maze[(x, y)] = EMPTY
            elif character == EXIT:
                exitx, exity = x, y
                maze[(x, y)] = EMPTY
        y += 1
    HEIGHT = y

    assert playerx != None and playery != None, 'No start in maze file.'
    assert exitx != None and exity != None, 'No exit in maze file.'

    maze_object = Maze(maze, WIDTH, HEIGHT, playerx, playery, exitx, exity)

    while True:                         # Main game loop
        maze_object.displayMaze(maze)

        while True:                     # Get user move
            print('                           W')
            print('Enter direction, or QUIT: ASD')
            move = input('> ').upper()

            if move == 'QUIT':
                print('Thanks for playing!')
                sys.exit()

            if move not in ['W', 'A', 'S', 'D']:
                print('Invalid direction. Enter one of W, A, S, or D.')
                continue

            # Check if the player can move in that direction
            # Note: change to use maze_object.player x and y
            if move == 'W' and maze[(maze_object.playerx, maze_object.playery - 1)] == EMPTY:
                break
            elif move == 'S' and maze[(maze_object.playerx, maze_object.playery + 1)] == EMPTY:
                break
            elif move == 'A' and maze[(maze_object.playerx - 1, maze_object.playery)] == EMPTY:
                break
            elif move == 'D' and maze[(maze_object.playerx + 1, maze_object.playery)] == EMPTY:
                break

            print('You cannot move in that direction.')

        # Keep moving in this direction until you encounter a branch point
        if move == 'W':
            while True:
                maze_object.playery -= 1
                if (maze_object.playerx, maze_object.playery) == (maze_object.exitx, maze_object.exity):
                    break
                if maze[(maze_object.playerx, maze_object.playery - 1)] == WALL:
                    break  # Break if we've hit a wall.
                if (maze[(maze_object.playerx - 1, maze_object.playery)] == EMPTY
                    or maze[(maze_object.playerx + 1, maze_object.playery)] == EMPTY):
                    break  # Break if we've reached a branch point.
        elif move == 'S':
            while True:
                maze_object.playery += 1
                if (maze_object.playerx, maze_object.playery) == (maze_object.exitx, maze_object.exity):
                    break
                if maze[(maze_object.playerx, maze_object.playery + 1)] == WALL:
                    break  # Break if we've hit a wall.
                if (maze[(maze_object.playerx - 1, maze_object.playery)] == EMPTY
                    or maze[(maze_object.playerx + 1, maze_object.playery)] == EMPTY):
                    break  # Break if we've reached a branch point.
        elif move == 'A':
            while True:
                maze_object.playerx -= 1
                if (maze_object.playerx, maze_object.playery) == (maze_object.exitx, maze_object.exity):
                    break
                if maze[(maze_object.playerx - 1, maze_object.playery)] == WALL:
                    break               # Break if we've hit a wall
                if (maze[(maze_object.playerx, maze_object.playery - 1)] == EMPTY
                    or maze[(maze_object.playerx, maze_object.playery + 1)] == EMPTY):
                    break               # Break if we've reached a branch point
        elif move == 'D':
            while True:
                maze_object.playerx += 1
                if (maze_object.playerx, maze_object.playery) == (maze_object.exitx, maze_object.exity):
                    break
                if maze[(maze_object.playerx + 1, maze_object.playery)] == WALL:
                    break               # Break if we've hit a wall
                if (maze[(maze_object.playerx, maze_object.playery - 1)] == EMPTY
                    or maze[(maze_object.playerx, maze_object.playery + 1)] == EMPTY):
                    break               # Break if we've reached a branch point

        # Win condition
        if (maze_object.playerx, maze_object.playery) == (maze_object.exitx, maze_object.exity):
            maze_object.displayMaze(maze)
            print('You have reached the exit! Good job!')
            print('Thanks for playing!')
            sys.exit()
            
if __name__ == "__main__":
    main()