import sys, os

WALL = '#'
EMPTY = ' '
START = 'S'
EXIT = 'E'

PLAYER = '@'            # (!) Try changing this to '+' or 'o'
BLOCK = chr(9617)       # Character 9617 is '░'

class Maze:
    def __init__(self, maze, WIDTH, HEIGHT, playerx, playery, exitx, exity):
        self.maze = maze
        self.WIDTH = WIDTH
        self.HEIGHT = HEIGHT
        self.playerx = playerx
        self.playery = playery
        self.exitx = exitx
        self.exity = exity
        print('''Maze Runner 2D

(Maze files are generated by mazemakerrec.py)''')
        
    def displayMaze(self, maze):
        # Display the maze:
        for y in range(self.HEIGHT):                        # Note: Need change to self.HEIGHT instead of HEIGHT from def main()
            for x in range(self.WIDTH):
                if (x, y) == (self.playerx, self.playery):
                    print(PLAYER, end='')
                elif (x, y) == (self.exitx, self.exity):
                    print('X', end='')
                elif maze[(x, y)] == WALL:
                    print(BLOCK, end='')
                else:
                    print(maze[(x, y)], end='')
            print()